# Generated by Django 5.1.7 on 2025-06-15 06:17

from django.db import migrations, models


def create_initial_data(apps, schema_editor):
    Client = apps.get_model('main', 'Client')
    Service = apps.get_model('main', 'Service')
    Project = apps.get_model('main', 'Project')

    # Add Clients
    Client.objects.create(name="FDH Bank")
    Client.objects.create(name="Press Properties Ltd")
    Client.objects.create(name="Sunbird")

    # Add Services
    Service.objects.create(title="Building Services", description="All building-related services.")
    Service.objects.create(title="Agriculture Engineering", description="Agriculture engineering solutions.")

    # Add Projects
    Project.objects.create(title="Office Complex", category="Building", description="A modern office complex.")
    Project.objects.create(title="Irrigation Scheme", category="Agriculture", description="Large-scale irrigation project.")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clients/')),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
            ],
        ),
        migrations.RunPython(create_initial_data),
    ]
